name: Gradle Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['23']
      fail-fast: true
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
        run: ./gradlew build